// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Movie struct {
	ID          uuid.UUID
	Title       string
	Rank        int32
	PeakRank    int32
	ReleaseYear int32
	Duration    int32
	Audience    string
	Rating      float64
	Votes       int32
	ImageSrc    string
	ImageAlt    string
	MovieUrl    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
